### ISSUE TITLE
Method to runAtEntityWithFallback with timer

### ISSUE THREAD

**Issue by PikaMug** [TechnicallyCoded/FoliaLib#12]
Would be useful for doing work when entities become dead/retired. For example, when adding a trail of particles behind a projectile. On Spigot/Paper I can just check Projectile#isDead and do some cleanup before manually cancelling the task, but that doesn't seem to happen on Folia; the server just ends the task. Thus, a fallback is necessary.

**Comment by TechnicallyCoded** [comment]
Will be implemented
