### ISSUE TITLE
1.8 Java support?

### ISSUE THREAD

**Issue by SuperRonanCraft** [TechnicallyCoded/FoliaLib#2]
I know its kinda dumb... but hear me out. BetterRTP, ur favorite plugin I know, needs to be able to run on any minecraft server version. 
Allowing this api to just default to the bukkit async/sync rules if folia just was not installed in any other java/minecraft version.

**Comment by Yomamaeatstoes** [comment]
@SuperRonanCraft

**Comment by SuperRonanCraft** [comment]
yoooooooooooooooo
🔥 🔥

**Comment by TechnicallyCoded** [comment]
Leaving open as there is still no long term support for this.

**Comment by ancap-kun** [comment]
Java doesn't break backward compatibility, so there is no reason to use old versions in any case.

**Comment by TechnicallyCoded** [comment]
That's not what we are talking about. You can run old java on new java but you can't run new java on old java.
Legacy 1.8 servers run old java (sometimes). This lib (other than the special legacy version), doesn't support old java runtimes.

**Comment by ancap-kun** [comment]
I mean we should force server owners to update their java and not downgrade our language level

**Comment by TechnicallyCoded** [comment]
That's what we want to believe but then we get 1 star reviews bc they really needed to use the most outdated version of paper that exists...
